# Generated by Django 5.0 on 2026-01-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('ANN', 'Artificial Neural Network'), ('SVM', 'Support Vector Machine')], max_length=10)),
                ('model_file', models.CharField(help_text='Path to model file', max_length=255)),
                ('accuracy', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_models',
            },
        ),
        migrations.CreateModel(
            name='XMLParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DOM', 'DOM Parser'), ('SAX', 'SAX Parser'), ('StAX', 'StAX Parser'), ('ElementTree', 'ElementTree Parser'), ('lxml', 'LXML Parser')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('best_for', models.TextField(help_text='Scenarios where this parser performs best')),
                ('memory_efficient', models.BooleanField(default=False)),
                ('speed_efficient', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xml_parsers',
            },
        ),
    ]
