# Generated by Django 5.0 on 2026-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xmlparser",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
