# Generated by Django 5.0 on 2026-01-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('xml_profiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserPerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size_mb', models.FloatField()),
                ('total_elements', models.IntegerField()),
                ('max_depth', models.IntegerField()),
                ('processor_cores', models.IntegerField()),
                ('parsing_time', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('efficiency_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.xmlparser')),
                ('xml_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_profiler.xmlfile')),
            ],
            options={
                'db_table': 'parser_performance_data',
            },
        ),
        migrations.CreateModel(
            name='ParsingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_time', models.FloatField(help_text='Time in seconds')),
                ('memory_used', models.FloatField(help_text='Memory in MB')),
                ('cpu_usage', models.FloatField(help_text='CPU usage percentage')),
                ('prediction_confidence', models.FloatField(default=0.0)),
                ('optimized_code', models.TextField(blank=True, null=True)),
                ('code_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ml_model_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mlmodel')),
                ('selected_parser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.xmlparser')),
                ('xml_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_profiler.xmlfile')),
            ],
            options={
                'db_table': 'parsing_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
